# Generated by Django 3.1.7 on 2021-03-22 20:33

import ProjectBot.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('discriminator', models.IntegerField()),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
                ('access_token', models.CharField(max_length=100)),
            ],
            managers=[
                ('objects', ProjectBot.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.CharField(max_length=70)),
                ('full_name', models.CharField(max_length=70)),
                ('msg_response', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUserGuilds',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('owner', models.BooleanField()),
                ('permissions', models.CharField(max_length=100)),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectBot.discorduser')),
            ],
        ),
    ]
