# Generated by Django 3.1.7 on 2021-03-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBot', '0002_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='msg_response',
            field=models.CharField(default='test response', max_length=255),
            preserve_default=False,
        ),
    ]
