# Generated by Django 3.1.7 on 2021-03-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBot', '0003_reporter_msg_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
    ]
