# Generated by Django 3.1.7 on 2021-03-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectBot', '0005_auto_20210321_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='discord_tag',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='discriminator',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discorduser',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
